### PR TITLE
Signup form clone from mint

### PR DESCRIPTION
**Pull request by karthi07**
cloned the signup page from mint's website

The original project was - 
https://github.com/karthi07/SignUp-page 

couldn't make pull request due to lint config files been added. hence create a new project to submit

### CODE REVIEW

**Comment by majovanilla** [comment]
# Code Review in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey team, 👋

## Good job on this project! 👍
You have a good look on your page.

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgithub.com%2Fkarthi07%2FSignUp%2Fblob%2Fsignup-page%2Fsignup.html). You have some errors and warnings. Please fix them.

- Always remember to activate your repo in Stickler. I cannot see your linters working!!

- Improve your Readme file. It should be descriptive of the project. Here's a great [template](https://github.com/microverseinc/readme-template) I strongly recommend you to use.

- Make the links on the page to look like the original one. Yours: have a different color blue, and the ones on the bottom should be gray.

- You can give a smaller width to the form and change the border color to make it look like the original one.



### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use semantic HTML for the main section (include a main tag  for the dominant content of the body)

- Take a look at this [page](https://icons8.com/) where you can find a lot of cool icons.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by uryelah** [comment]
### Code under review by Sarah Uryelah Silva Chamorro (TSE)

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Consider using the Microverse template for the 'readme' file, and please fill it with the information required on the template, [here](https://github.com/microverseinc/readme-template) you can see it.

- [ ] Consider making a smaller width to the form to make it look like the original one.

- [ ] Consider adding the color 'blue' on the propper links in your entire page as the original page (except the footer links).

Screenshot from 2020-02-24 10-45-31

- [ ] Consider adding this links in your page as the original page:

Screenshot from 2020-02-24 10-45-31

Screenshot from 2020-02-24 10-41-38

- [ ] Footer links have to be in a gray color as the original.

[OPTIONAL]

- [ ] Consider adding a screenshot of your project in your readme file.

- [ ] I encourage you to use the `<nav>` tag for the major navigation links.

- [ ] I encourage you to use the `<main>` tag for the dominant content of the `<body>` of a document.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Review by nikasulo — APPROVED** [review]
# Great job @MrSayyod  and @karthi07 
You have done a beautiful job implementing the required changes suggest by @majovanilla :clap:. That being said, you may merge and keep moving forward 😊.

You may also consider the optional changes she suggested, they will really improve your project if you can make them. I wish you all the best, and see you at the top 🚀

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
